# Generated by Django 5.0.4 on 2024-04-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.PositiveIntegerField()),
                ('good_driver', models.BooleanField(default=False, verbose_name='Do you think you are a good driver?')),
                ('speeding_ticket', models.BooleanField(default=False, verbose_name='Have you ever gotten a speeding ticket?')),
                ('car_crash', models.BooleanField(default=False, verbose_name='Have you ever been in a car crash?')),
                ('employed', models.BooleanField(default=False, verbose_name='Do you have a job?')),
            ],
        ),
    ]
