# Generated by Django 5.0.4 on 2024-05-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_driver_enjoy_cooking_driver_enjoy_outdoor_activities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='car_crash',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='employed',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='enjoy_cooking',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='enjoy_outdoor_activities',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='enjoy_scifi_movies',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='good_driver',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='interested_in_fitness',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='morning_person',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='pet_owner',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='prefer_reading_fiction',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='prefer_texting_over_calling',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='speeding_ticket',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='tech_savvy',
        ),
        migrations.AddField(
            model_name='driver',
            name='abortion_rights_support',
            field=models.BooleanField(default=False, verbose_name="Do you believe in a woman's right to choose abortion?"),
        ),
        migrations.AddField(
            model_name='driver',
            name='affirmative_action_support',
            field=models.BooleanField(default=False, verbose_name='Do you support affirmative action policies to address discrimination and promote diversity?'),
        ),
        migrations.AddField(
            model_name='driver',
            name='censorship_laws_support',
            field=models.BooleanField(default=False, verbose_name='Do you believe in stricter censorship laws to regulate online content?'),
        ),
        migrations.AddField(
            model_name='driver',
            name='climate_change_belief',
            field=models.BooleanField(default=False, verbose_name='Do you believe that climate change is primarily caused by human activities?'),
        ),
        migrations.AddField(
            model_name='driver',
            name='death_penalty_support',
            field=models.BooleanField(default=False, verbose_name='Do you support the use of the death penalty for certain crimes?'),
        ),
        migrations.AddField(
            model_name='driver',
            name='gun_control_support',
            field=models.BooleanField(default=False, verbose_name='Do you support stricter gun control laws?'),
        ),
        migrations.AddField(
            model_name='driver',
            name='immigration_policies_support',
            field=models.BooleanField(default=False, verbose_name='Do you support stricter immigration policies and border control?'),
        ),
        migrations.AddField(
            model_name='driver',
            name='marijuana_legalization_support',
            field=models.BooleanField(default=False, verbose_name='Do you support the legalization of marijuana for recreational use?'),
        ),
        migrations.AddField(
            model_name='driver',
            name='universal_basic_income_support',
            field=models.BooleanField(default=False, verbose_name='Do you support the implementation of a universal basic income for all citizens?'),
        ),
        migrations.AddField(
            model_name='driver',
            name='vaccination_mandates_support',
            field=models.BooleanField(default=False, verbose_name='Do you support mandatory vaccinations for children to attend school?'),
        ),
    ]
